### PR TITLE
Contributors Section

### PR DESCRIPTION
**Pull request by Techno-Simpola**
Solved issue #109 
I added templates containing bootstrap cards and modified CSS.
Mehul already added backend previously in web team app.

### CODE REVIEW

**Comment by Techno-Simpola** [comment]
@Prakhar19999 @sayanp99 @Subhajoy123 @amish1999 @Abha2001 @Shriya99
please review the changes made.

**Comment by Prakhar19999** [comment]
Screenshot from 2021-07-03 23-23-37

**Comment by Prakhar19999** [comment]
Cards must be displayed in single row

**Comment by Techno-Simpola** [comment]
@Prakhar19999 @Shriya99 @sayanp99 @Subhajoy123 @spaceySama @Abha2001 @
Please review the changes made

**Comment by Prakhar19999** [comment]
(1)Hover Shadow-White
(2)Logo and Name-Black
(3)Make name and logo position more centralized

**Comment by Subhajoy123** [comment]
1. Remove the image enlarging part
2. Align the name and logo properly with adequate space in top and bottom
3. both name and logo orange in color
4. keep the hover background black only

**Review by Prakhar19999 — APPROVED** [review]

**Review by sayanp99 — APPROVED** [review]

**Review by Subhajoy123 — APPROVED** [review]

**Pull request merged**
