### PR TITLE
integrated dynamic countdown timer( for upcoming events and ongoing events) and sub-navbar for event's page.

### PR DESCRIPTION
**Pull request by Purvi2401**

### CODE REVIEW

**Comment by Prakhar19999** [comment]
Modify the active css class for subnav bar in event_registration

**Comment by Subhajoy123** [comment]
The back-to-top button is not working in the Events page. The active class is not working properly in the mobile view.

**Comment by Prakhar19999** [comment]
After clicking on any of subnavbar button twice, the button stays active even after scrolling

**Review by Prakhar19999 — APPROVED** [review]
**Nice Work!** @Purvi2401

**Comment by sayanp99** [comment]
@Purvi2401 there are a few minor changes:
1. In mobile view its still not showing 2 in a row for Iphone-X, make sure to do that since it is the standard mobile ratio.
2. in place of "NaN" you can use something better and formal like NIL or NA etc.
3. Gap between the subsections is more than required, reduce them.
4. Also when the page opens, there is a default gap before the ONGOING EVENTS section which is not required, the default gap should be same as that of what happens when we click the ONGOING EVENTS button from the sub-navbar

Make sure to fix this changes, apart from that rest is fine. Good Work!

**Review by sayanp99 — CHANGES_REQUESTED** [review]
@Purvi2401 there are a few minor changes:

1. In mobile view its still not showing 2 in a row for Iphone-X, make sure to do that since it is the standard mobile ratio.
2. In place of "NaN" you can use something better and formal like NIL or NA etc.
3. Gap between the subsections is more than required, reduce them.
4. Also when the page opens, there is a default gap before the ONGOING EVENTS section which is not required, the default gap should be same as that of what happens when we click the ONGOING EVENTS button from the sub-navbar

Make sure to fix this changes, apart from that rest is fine. Good Work!

**Review by sayanp99 — APPROVED** [review]

**Review by Prakhar19999 — APPROVED** [review]

**Review by amish1999 — APPROVED** [review]

**Review by Subhajoy123 — APPROVED** [review]

**Review by Shriya99 — APPROVED** [review]

**Comment by Shriya99** [comment]
Good progress Purvi

**Pull request merged**
